baseURL = "https://blog.edouardmenayde.fr/"
languageCode = "en-us"
title = "Edouard Menayde's blog"
theme = "hyde"
pygmentsCodeFences=true

[author]
  name = "Edouard Menayde"
  url = "https://edouardmenayde.fr/"

[params]
  themeColor = "theme-base-08"
  description = "Edouard Menayde's blog, talks about code especially Elixir, Ecto and Phoenix."

[Menus]
  main = [
      {Name = "Professional website", URL = "https://edouardmenayde.fr/"},
      {Name = "Github", URL = "https://github.com/edouardmenayde/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/edouard-menayde-b17626135/"}
  ]
